In [3]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from keras.datasets import mnist
from keras.layers import Dense, Flatten, Conv2D, AveragePooling2D
from keras.models import Sequential
import tensorflow as tf

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))



In [4]:
mnist = tf.keras.datasets.mnist.load_data()

In [5]:
mnist

((array([[[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         ...,
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0

In [6]:
(X_train, y_train), (X_test, y_test) = mnist

In [7]:
X_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [8]:
X_train = X_train.reshape(X_train.shape[0], 28,28,1)
X_train
X_test = X_test.reshape(X_test.shape[0], 28,28,1)
X_test

array([[[[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        ...,

        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]]],


       [[[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        ...,

        [[0],
         [0],
         [0],
         ...,
         [0],


In [9]:
#Normalization 
X_train = X_train / 255
X_test = X_test / 255

In [10]:
X_train.shape

(60000, 28, 28, 1)

In [11]:
#converting it into one hot encoding [0,0,0,0,0,1,0,0,0]
y_train = tf.keras.utils.to_categorical(y_train, 10)
y_test = tf.keras.utils.to_categorical(y_test, 10)
y_test[0]


array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.], dtype=float32)

In [12]:
model = Sequential()#Sequential groups a linear stack of layers
model.add(Conv2D(6,kernel_size=(5,5), padding = 'valid', activation='tanh', input_shape=(28,28,1))) #given in research paper of nenet-5
model.add(AveragePooling2D(pool_size=(2,2), strides = 2, padding='valid'))
model.add(Conv2D(16,kernel_size=(5,5), padding = 'valid', activation='tanh')) #given in research paper
model.add(AveragePooling2D(pool_size=(2,2), strides = 2, padding='valid'))
model.add(Flatten())#Flattens the input. Does not affect the batch size
model.add(Dense(120, activation='tanh'))
model.add(Dense(84, activation='tanh'))
model.add(Dense(10, activation='softmax'))
model.summary()



2023-01-18 13:28:27.343253: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-01-18 13:28:27.455584: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-01-18 13:28:27.456741: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-01-18 13:28:27.459737: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compil

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 24, 24, 6)         156       
_________________________________________________________________
average_pooling2d (AveragePo (None, 12, 12, 6)         0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 8, 8, 16)          2416      
_________________________________________________________________
average_pooling2d_1 (Average (None, 4, 4, 16)          0         
_________________________________________________________________
flatten (Flatten)            (None, 256)               0         
_________________________________________________________________
dense (Dense)                (None, 120)               30840     
_________________________________________________________________
dense_1 (Dense)              (None, 84)                1

In [13]:
(120*256+120) + (84*120+84) + (84*10+10) + 2416 + 156

44426

In [14]:
6*28

168

In [15]:
EarlyStop = tf.keras.callbacks.EarlyStopping(monitor='loss', patience = 4)

In [16]:
model.compile(loss=tf.keras.metrics.categorical_crossentropy, optimizer = tf.keras.optimizers.Adam(), metrics=['accuracy'])

In [17]:
model.fit(X_train, y_train, batch_size=120, epochs = 10,validation_data=(X_test, y_test),callbacks=[EarlyStop])

2023-01-18 13:28:35.757670: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)


Epoch 1/10


2023-01-18 13:28:37.774034: I tensorflow/stream_executor/cuda/cuda_dnn.cc:369] Loaded cuDNN version 8005


500/500 [==============================] - 12s 7ms/step - loss: 0.3551 - accuracy: 0.8982 - val_loss: 0.1643 - val_accuracy: 0.9524
Epoch 2/10
500/500 [==============================] - 3s 6ms/step - loss: 0.1333 - accuracy: 0.9596 - val_loss: 0.0950 - val_accuracy: 0.9693
Epoch 3/10
500/500 [==============================] - 3s 6ms/step - loss: 0.0882 - accuracy: 0.9733 - val_loss: 0.0754 - val_accuracy: 0.9762
Epoch 4/10
500/500 [==============================] - 3s 6ms/step - loss: 0.0665 - accuracy: 0.9793 - val_loss: 0.0590 - val_accuracy: 0.9813
Epoch 5/10
500/500 [==============================] - 3s 7ms/step - loss: 0.0515 - accuracy: 0.9840 - val_loss: 0.0540 - val_accuracy: 0.9820
Epoch 6/10
500/500 [==============================] - 3s 6ms/step - loss: 0.0439 - accuracy: 0.9863 - val_loss: 0.0549 - val_accuracy: 0.9821
Epoch 7/10
500/500 [==============================] - 3s 6ms/step - loss: 0.0364 - accuracy: 0.9883 - val_loss: 0.0519 - val_accuracy: 0.9828
Epoch 8/10
500/5

In [18]:
score = model.evaluate(X_test, y_test)

print("Test loss",score[0])
print("test Accuracy" , score[1])

313/313 [==============================] - 1s 4ms/step - loss: 0.0514 - accuracy: 0.9841
Test loss 0.05135965719819069
test Accuracy 0.9840999841690063


In [21]:
from tensorflow.keras.layers import Activation,MaxPooling2D, BatchNormalization, Dropout
from tensorflow.keras import Sequential

In [20]:
from keras import layers

In [21]:
from tensorflow.keras.layers import Activation,MaxPooling2D, BatchNormalization, Dropout
from tensorflow.keras import Sequential

In [24]:
from tensorflow.keras import datasets, layers, models, losses


In [29]:
mnist = tf.keras.datasets.mnist.load_data()
(X_train, y_train), (X_test, y_test) = mnist
X_train = tf.pad(X_train, [[0, 0], [2,2], [2,2]])/255
X_test = tf.pad(X_test, [[0, 0], [2,2], [2,2]])/255

#X_train = tf.expand_dims(X_train, axis=3, name=None)
#X_test = tf.expand_dims(X_test, axis=3, name=None)
#x_train = tf.repeat(X_train, 3, axis=3)
#x_test = tf.repeat(x_test, 3, axis=3)
#x_val = x_train[-2000:,:,:,:]
#y_val = y_train[-2000:]
#x_train = x_train[:-2000,:,:,:]
#y_train = y_train[:-2000]

In [30]:
X_train = tf.expand_dims(X_train, axis=3, name=None)
X_test = tf.expand_dims(X_test, axis=3, name=None)

In [32]:
#Repeat elements of input.
X_train = tf.repeat(X_train, 3, axis=3)
X_test = tf.repeat(X_test, 3, axis=3)

In [33]:
X_val = X_train[-2000:,:,:,:]
y_val = y_train[-2000:]
X_train = X_train[:-2000,:,:,:]
y_train = y_train[:-2000]

In [34]:
model = models.Sequential()
model.add(layers.experimental.preprocessing.Resizing(224, 224, interpolation="bilinear", input_shape=X_train.shape[1:]))
model.add(layers.Conv2D(96, 11, strides=4, padding='same'))
model.add(layers.Lambda(tf.nn.local_response_normalization))
model.add(layers.Activation('relu'))
model.add(layers.MaxPooling2D(3, strides=2))
model.add(layers.Conv2D(256, 5, strides=4, padding='same'))
model.add(layers.Lambda(tf.nn.local_response_normalization))
model.add(layers.Activation('relu'))
model.add(layers.MaxPooling2D(3, strides=2))
model.add(layers.Conv2D(384, 3, strides=4, padding='same'))
model.add(layers.Activation('relu'))
model.add(layers.Conv2D(384, 3, strides=4, padding='same'))
model.add(layers.Activation('relu'))
model.add(layers.Conv2D(256, 3, strides=4, padding='same'))
model.add(layers.Activation('relu'))
model.add(layers.Flatten())
model.add(layers.Dense(4096, activation='relu'))
model.add(layers.Dropout(0.5))
model.add(layers.Dense(4096, activation='relu'))
model.add(layers.Dropout(0.5))
model.add(layers.Dense(10, activation='softmax'))
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
resizing (Resizing)          (None, 224, 224, 3)       0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 56, 56, 96)        34944     
_________________________________________________________________
lambda (Lambda)              (None, 56, 56, 96)        0         
_________________________________________________________________
activation (Activation)      (None, 56, 56, 96)        0         
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 27, 27, 96)        0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 7, 7, 256)         614656    
_________________________________________________________________
lambda_1 (Lambda)            (None, 7, 7, 256)        

In [35]:
1024*4096 +4096

4198400

In [37]:
model.compile(optimizer='adam', loss=losses.sparse_categorical_crossentropy, metrics=['accuracy'])
history = model.fit(X_train, y_train, batch_size=64, epochs=40, validation_data=(X_val, y_val))

Epoch 1/40
 32/907 [>.............................] - ETA: 1:03 - loss: 2.2211 - accuracy: 0.1372

KeyboardInterrupt: 

In [ ]:
model.evaluate(x_test, y_test)


In [ ]:
fig, axs = plt.subplots(2, 1, figsize=(15,15))
axs[0].plot(history.history['loss'])
axs[0].plot(history.history['val_loss'])
axs[0].title.set_text('Training Loss vs Validation Loss')
axs[0].set_xlabel('Epochs')
axs[0].set_ylabel('Loss')
axs[0].legend(['Train', 'Val'])
axs[1].plot(history.history['accuracy'])
axs[1].plot(history.history['val_accuracy'])
axs[1].title.set_text('Training Accuracy vs Validation Accuracy')
axs[1].set_xlabel('Epochs')
axs[1].set_ylabel('Accuracy')
axs[1].legend(['Train', 'Val'])